### ISSUE TITLE
Vehicle paint: applying pearlescent topcoat to metallic also changes base colour

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#66]
I haven't tried this in detail but it appears to behave as above.

**Comment by TSM4278** [comment]
Works fine for me, same as always? Just tested in v15.

**Comment by gtav-ent** [comment]
It doesn't always break, but something weird happens to it. Try picking chrome or a wheel colour first, maybe that does it.

**Comment by TSM4278** [comment]
Ok, I'll try to play around a bit with that and see what happens.

**Comment by TSM4278** [comment]
Actually, I bet I know what triggers it. I accidentally left wheel color as a selectable paint type (it was only meant to be used when choosing to color wheels, which is handled differently now anyways). If you try to apply wheel paint colors as a primary paint color the values will not line up with the expected color and can be out of the intended range. That may be the root of the problem. I'll keep testing around and push an update to remove wheel colors anyway as it is now unnecessary and confusing to have them as an available paint type.

**Comment by TSM4278** [comment]
Come to think of it, here's another thing that's probably confusing people. Pearlescent topcoat can only be applied to a basecoat of pearlescent (type 2). In LSC the game switches the basecoat to type 2 if you have a metallic basecoat (type 0) and select a pearlescent topcoat.

The paint menu will (currently) allow you to select a pearlescent topcoat and apply it to any underlying color, it will then switch the basecoat to type 2. The paint menu mirrors the functionality of LSC when painting with a metallic basecoat and then applying a pearlescent topcoat (as intended). It also will handle a switch from normal paint (type 1) the same as from metallic (not an original game feature, but the color list is identical and the switch is transparent to the user, so why not?)

However, If you select matte blue (type 4, paint 4) and try to apply pearlescent on top of that (not an intended feature), the paint menu will switch the basecoat type to Type 2 and keep the value of paint 4. Which will correspond to a value of "Black steel" as the basecoat with whatever pearl you have applied on top of it. This is because the underlying color values are identical between normal/metallic/pearlescent, but not for the other paint types.

 I originally had a check see if the basecoat was type 2 and would only apply pearlescent if it was. Now the menu will just override all paint types and switch them to type 2 if pearl is selected. Easier on the user and no error messages, but when trying to put pearl on an incompatible basecoat the color will seem to switch as the game handles the new values differently. I guess a check is needed to rebuff only attempts to use pearlescent on top of matte/metal/chrome.

I just didn't think this would be an issue as you couldn't do it in the base game anyway, but I think that was a mistake and I'll update the paint menu with the extra checks (as well as the menu indexing you wanted) when I get a chance to sit down with it again.

**Comment by gtav-ent** [comment]
This is done in u26.
