### ISSUE TITLE
Vehicle paint: Add chrome to wheels

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#74]
I haven't checked if this is in the latest pull requests, but it was reported as missing after initially existing, possibly by mistake.

**Comment by TSM4278** [comment]
That was never in there in the first place. If anyone managed to do it I'd love to know how myself. :)

I think a lot of people just got really confused with the paint menu system. All paint options were initially shown even when they were not applicable. The player was expected to select paint wheels -> wheel paint, or paint primary -> chrome paint. Trying it the other way around would just use a different set of color names, but would otherwise not have the intended effect. 

Hopefully it will be less confusing now that those unnecessary options are no longer visible.

**Comment by gtav-ent** [comment]
This was probably the result of a bug, but:

http://gtaforums.com/topic/789786-vrelwip-enhanced-native-trainer/?p=1067494136

It's a bit weird because AFAIK it's not actually an option in the game.

**Comment by TSM4278** [comment]
Hmm, that seems to relate to the vehicle mod menu and what it defaults to when it changes a wheel, not the paint menu. I haven't looked closely at it since you integrated it into the new menu system but I have no idea why anything would change. It just sets the wheel type and should spawn in at whatever the default color the wheel is set to by the game (chrome can only be on chrome wheels as it is a texture issue not a color change issue, as far as I understand it anyway)

**Comment by TSM4278** [comment]
I don't know which wheels that car uses by default, but could the user be mixing up the default wheel type with the (similar, but different) variant found in the wheel type submenu?

**Comment by gtav-ent** [comment]
I had a look at this and I can't figure it out either, so I'm closing the issue.

**Comment by gtav-ent** [comment]
FYI I found that the answer to this was that there is a whole second set of chrome wheels after the original indices (e.g. normal wheels 1-25, then chrome 26-50).
