### ISSUE TITLE
Add 'radio always off' option

### ISSUE THREAD

**Issue by gtav-ent** [gtav-ent/GTAV-EnhancedNativeTrainer#85]
This belongs with the other radio options in I think Misc.

**Comment by dratom** [comment]
I tried writing this feature into the native trainer included with the original script hook when it was first released. I failed. But that was ages ago and there have been leaps in terms of the number of deciphered API names and their arguments since then.
Turning off the radio every time you get into a new vehicle is pretty annoying. The alternative which is to mute the radio function in the player options menu is not very appealing as there are plenty of times when I enjoy listening to the radio stations.

It would also be nice to be able to set a default station

**Comment by gtav-ent** [comment]
This (radio always off) will be in the next update, 24. If you want a default station, raise a new issue.
